CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lanterns (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mac_address CHAR(12) NOT NULL UNIQUE,
    user_id INT UNSIGNED NOT NULL,
    address VARCHAR(1024) NOT NULL,
    lantern_brightness TINYINT UNSIGNED NOT NULL DEFAULT 100 CHECK (lantern_brightness BETWEEN 0 AND 100),
    night_brightness TINYINT UNSIGNED NOT NULL DEFAULT 20 CHECK (night_brightness BETWEEN 0 AND 100),
    night_start TINYINT UNSIGNED NOT NULL DEFAULT 22 CHECK (night_start BETWEEN 0 AND 23),
    night_end TINYINT UNSIGNED NOT NULL DEFAULT 8 CHECK (night_end BETWEEN 0 AND 23),
    color_temperature TINYINT NOT NULL DEFAULT 0 CHECK (color_temperature BETWEEN -5 AND 5),
    flicker_intensity DECIMAL(4,2) NOT NULL DEFAULT 1.00 CHECK (flicker_intensity BETWEEN 0.1 AND 10),
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT lanterns_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;